[font]
  bold_italic = { family = "Cascadia Code NF SemiBold", style = "Italic" }
       italic = { family = "Cascadia Code NF",          style = "Italic" }
       normal = { family = "Cascadia Code NF",          style = "Medium" }
         bold = { family = "Cascadia Code NF",          style = "Bold" }

[colors.primary]
  background = "#0a1124"

[window]
blur = true
opacity = 0.965
